### ISSUE TITLE
Problems defining corosync_interfaces via playbook yml

### ISSUE THREAD

**Issue by gamename** [sbitio/ansible-corosync#2]
Hi,

This looks like a very cool role. But I'm having problems using it. 

Can you explain how this (below) from [`defaults/main.yml`](https://github.com/sbitmedia/ansible-corosync/blob/master/defaults/main.yml) file:

``` yaml
#corosync_interfaces:
# - bindnetaddr:
#   broadcast:
#   mcastaddr:
#   mcastport:
#   ttl:
#   members:
#     - ip1
#     - ip2
# - bindnetaddr:
#   broadcast:
#   mcastaddr:
#   mcastport:
#   ttl:
#   members:
#     - ip1
#     - ip2
```

Would translate into a yaml construct in a playbook?  I tried this:

``` yaml
      - name: Configure corosync
        corosync_interfaces:
          bindnetaddr: "192.168.42.101"
          mcastport: 5405
          ttl: 1
          members:
              - 192.168.42.101
              - 192.168.42.102
```

and got this error:

```
==> pg-primary: Running provisioner: ansible...
ERROR: corosync_interfaces is not a legal parameter in an Ansible task or handler
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

So, how should the construct look in a playbook if I want to define the interfaces there?  
Thanks.
-T
